- name: setting up docker
  hosts: all
  tasks:
    - name: install python-pip
      apt:
        name: python-pip
        state: present
        update_cache: yes
    - name: install docker
      shell: "{{ item}}"
      loop: 
        - curl -fsSL https://get.docker.com -o get-docker.sh
        - sh get-docker.sh
